//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOkopedia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumDetail
    {
        public int ForumId { get; set; }
        public int UserId { get; set; }
        public string Review { get; set; }
        public System.DateTime PostDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
